### ISSUE TITLE
New xtypes for sexagesimal angles

### ISSUE THREAD

**Issue by mbtaylor** [ivoa-std/DALI#22]
There is currently no good way to indicate that a VOTable FIELD/PARAM contains a sexagesimal representation of an angle.  Common practice in VizieR is to use a value of ``'h:m:s'`` or ``'d:m:s'``, but these are not units.  Client code might infer that string values with UCDs indicating celestial coordinates are sexagesimal, but it's a bit hacky.

I would like to see two new xtypes in DALI to indicate string values that represent angles in sexagesimal hours:minutes:seconds and degrees:minutes:seconds.  Presumably these would be xtypes "``hms``" and "``dms``".

**Comment by pdowler** [comment]
Agree.

**Comment by pdowler** [comment]
I'm working on a PR with xtype="range" and removing multipolygon from shape, so will add these at the same time.

**Comment by pdowler** [comment]
this is in PR #24
