### ISSUE TITLE
Update reference to RDF examples vocabulary

### ISSUE THREAD

**Issue by mbtaylor** [ivoa-std/DALI#23]
Section 2.3 describing RDFa markup of DALI examples documents currently contains the text:
> In future, this URL may resolve to an RDF vocabulary document in human and machine-readable format(s) and if so will contain the normative list of values for the property attribute and will supersede the ones specified below.

Following endorsement of the http://www.ivoa.net/rdf/examples vocabulary at the TCG meeting in Bologna this future has arrived, so the text should be updated.  Markus is probably best placed to make this update.

**Comment by msdemlei** [comment]
@mbtaylor: If you're happy with what happened in PR #25, would you close this?  Thanks!
