### ISSUE TITLE
Multipolygon delimiter format/examples

### ISSUE THREAD

**Issue by mbtaylor** [ivoa-std/DALI#36]
According to Sec 3.11 of the current WD, `xtype="multipolygon"` allows specification of several polygons in one value, by giving multiple vertex sequences separated by a delimiter.  The current WD-DALI-1.2 text says:
> The array holds a sequence of non-overlapping polygon(s) separated by a NaN value.

It used to say additionally:
> NOTE: Prototypes will determine if a single NaN value (as above) or two adjacent NaN values (a NaN point) is easier to serialise, parse, and validate.

but this text was dropped at 32b007f22b (I can't figure out what PR that came in at).

My implementation experience is that two adjacent NaN values are easier to handle in geometry-consuming code.  Given the current text however I'm trying to update my implementation to work with a single NaN as delimiter instead.  However I haven't so far found any examples of `xtype="multipolygon"` data in the wild.  So:
1. Can anybody point to multipolygon data following the current DALI proposal?
2. If not, can we reconsider whether the 2-NaN separator is preferable?

**Comment by pdowler** [comment]
That note/commit was from me... it seemed like we weren't going to resolve that item without going to RFC so I just picked the smallest serialization. I've implemented code to parse both but I'll have to go back and look at them again and see what I was thinking at the time.

I still have to update our main tap service to output multipolygon (we have the content)... it's on my list of things to do asap.
